### ISSUE TITLE
Exchange_time and received_time are the same

### ISSUE THREAD

**Issue by yolonir** [barter-rs/barter-data-rs#27]
Hi! I am running this example:
https://github.com/barter-rs/barter-data-rs/blob/develop/examples/public_trades_streams.rs

Unfortunately I have rather doubtful results

```MarketEvent<OrderBookL1>: MarketEvent { exchange_time: 2023-02-06T17:52:17.056798Z, received_time: 2023-02-06T17:52:17.056798Z, exchange: binance_futures_usd, instrument: Instrument { base: btc, quote: usdt, kind: FuturePerpetual }, kind: OrderBookL1 { last_update_time: 2023-02-06T17:52:17.056798Z, best_bid: Level { price: 23041.9, amount: 0.205 }, best_ask: Level { price: 23042.0, amount: 17.663 } } }```

Exchange and receive time are the same, I doubt that it is due to hyper fast benefits of this lib, any suggestions? Is this a bug?

**Comment by jnatherley** [comment]
![Screenshot 2023-02-13 at 19 11 55](https://user-images.githubusercontent.com/2078999/218538677-c6caafb1-0dce-463e-937f-35c989b8c833.png)

Could it be in the nano-seconds @just-a-stream

**Comment by just-a-stream** [comment]
Hello :)

Thanks for bringing this to my attention. I've improved the situation in barter-data-rs release 0.6.9!

BinanceFuturesUsd now uses the correct timestamp. 

However, since the BinanceSpot server does not provide a timestamp for the payload I've had to use the same as received timestamp.

Hope this seems reasonable for you!

Thanks, JustAStream
